project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!activity_templates/"
    - "!assignments/"
    - "!working/"
  post-render: "cp -r activities docs/activity_templates" # adds activity qmd as downloadable template
  resources:
    - "data/*.csv"
    # - "activity_templates/*.qmd"
    - "assignments/*.qmd"
    - .nojekyll

website:
  title: "STAT 253"
  site-url: https://mutasim221B.github.io/Mac-STAT-253-Sp-26/
  repo-url:  https://github.com/mutasim221b/Mac-STAT-253-Sp-26
  favicon: favicon-32x32.png
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Welcome!"
      - sidebar:overview
      - sidebar:activities
      - sidebar:appendices


  sidebar:
    - id: overview
      title: "Course Logistics"
      contents:
          - "syllabus.qmd"
          - "learning.qmd"
          - "getting-started.qmd"

    - id: activities
      title: "Activities"
      contents:
          - "activities/L01-introductions.qmd"
          - "activities/L02-evaluating-regression-models.qmd"
          - "activities/L03-Overfitting.qmd"

    - id: appendices
      title: "Appendices"
      contents:
          - "R_Rstudio.qmd"
          - "R_Resources.qmd"
          - "stat155.qmd"

  
  page-footer:
    left: |
      &copy; Md Mutasim Billah, 2026<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: sandstone
    # css: styles.css
    toc: true      
    code-overflow: wrap

editor: source
